// clang-format off
#ifndef OPENTXS_PROTO_VERSION_HPP
#define OPENTXS_PROTO_VERSION_HPP

#define OPENTXS_PROTO_VERSION_MAJOR @VERSION_MAJOR@
#define OPENTXS_PROTO_VERSION_MINOR @VERSION_MINOR@
#define OPENTXS_PROTO_VERSION_BUGFIX @VERSION_BUGFIX@
#define OPENTXS_PROTO_VERSION_HASH "@VERSION_SHA1@"
#define OPENTXS_PROTO_VERSION_STRING "@VERSION_STRING@"

#endif // OPENTXS_PROTO_VERSION_HPP
// clang-format on
